name: merge

on:
  release:
    types: [ published ]

env:
  SERVICE_NAME: secureopenbanking-uk-fidc-initializer

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Tests
        run: |
          make test-ci

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCR_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

        # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker
      
      - name: docker build
        run: |
          make docker release-repo=${{ secrets.RELEASE_REPO }}
